#!/bin/sh
#
# Daemontools init for varnishd
# 
MEMLIMIT="4294967296"

exec 2>&1
exec /command/softlimit -m $MEMLIMIT /usr/local/sbin/varnishd -a :81 \
    -T localhost:6082 \
    -f /etc/vpmc.vcl \
    -h classic \
    -s malloc,1024M \
    -F
